preload = /home/scharyk/linux_betterwindows/Wallpapers/devushka_anime_art_1324929_1920x1080.jpg
wallpaper = eDP-1,/home/scharyk/linux_betterwindows/Wallpapers/devushka_anime_art_1324929_1920x1080.jpg
