preload = /home/scharyk/linux_betterwindows/Wallpapers/leto_rastitelnost_nadpis_145251_1920x1080.jpg
wallpaper = eDP-1,/home/scharyk/linux_betterwindows/Wallpapers/leto_rastitelnost_nadpis_145251_1920x1080.jpg
