preload = /home/scharyk/linux_betterwindows/Wallpapers/devushka_maska_obodok_1139089_1920x1080.jpg
wallpaper = eDP-1,/home/scharyk/linux_betterwindows/Wallpapers/devushka_maska_obodok_1139089_1920x1080.jpg
